"""
gui_utils.py - GUI通用工具函数和常量
"""
import os
from PySide6 import QtCore, QtGui

# 日志级别颜色映射
LOG_COLORS = {
    "info": "#000000",
    "warning": "#c07a00",
    "error": "#c00000",
    "success": "#008000"
}

# 语言包配置
LANGUAGE_PACKS = {
    "zh": {
        "window_title": "STZ压缩解压工具",
        "btn_help": "帮助",
        "tab_compress": "文件压缩",
        "tab_decompress": "文件解压",
        "tab_modify": "修改压缩包",
        "tab_analyze": "压缩率分析",
        "btn_add_files": "添加文件",
        "btn_add_folders": "添加文件夹",
        "btn_add_folder": "添加文件夹",
        "btn_remove": "移除选中",
        "btn_clear": "清空",
        "btn_clear_list": "清空列表",
        "check_password": "使用密码加密",
        "edit_password": "密码",
        "use_custom_dictionary": "使用自定义字典",
        "status_compressing": "压缩中...",
        "status_decompressing": "解压中...",
        "status_paused": "已暂停",
        "status_cancelled": "已取消",
        "status_completed": "完成",
        "btn_compress_start": "开始压缩",
        "btn_decompress_start": "开始解压",
        "btn_modify_start": "保存修改",
        "btn_start_analyze": "开始分析",
        "btn_browse": "浏览...",
        "btn_browse_compress": "浏览...",
        "btn_browse_decompress": "浏览...",
        "btn_browse_modify": "浏览...",
        "btn_load_content": "加载内容",
        "btn_preview_content": "预览内容",
        "btn_pause": "暂停",
        "search": "搜索:",
        "btn_cancel": "取消",
        "btn_extract": "提取选中文件",
        "btn_delete": "删除选中文件",
        "btn_addnew": "添加新文件",
        "btn_replace": "替换选中文件",
        "btn_stz_to_zip": "STZ -> ZIP",
        "btn_zip_to_stz": "ZIP -> STZ",
        "btn_batch_decompress": "批量解压多个STZ",
        "btn_save_modify": "保存修改",
        "compress_level": "压缩级别:",
        "split_size": "分卷大小 (MB):",
        "only_new": "仅新增/修改 (增量)",
        "delete_source": "压缩后删除源文件",
        "output_file": "输出文件 (.stz):",
        "compress_file": "选择压缩包 (.stz):",
        "decompress_dir": "解压目录:",
        "theme_label": "主题:",
        "theme_system": "系统默认",
        "theme_light": "浅色主题",
        "theme_dark": "深色主题",
        "language_label": "语言:",
        "language_zh": "中文",
        "language_en": "English",
        "guide_title": "操作引导",
        "guide_welcome": "欢迎使用STZ压缩解压工具！",
        "guide_steps": "使用步骤：\n1. 压缩文件：\n   - 点击'添加文件'或'添加文件夹'选择要压缩的内容\n   - 设置压缩级别、密码等参数\n   - 选择输出路径，点击'开始压缩'\n2. 解压文件：\n   - 选择要解压的压缩包\n   - 设置解压目标目录\n   - 点击'开始解压'\n3. 修改压缩包：\n   - 选择要修改的压缩包\n   - 添加或删除文件\n   - 点击'保存修改'\n4. 压缩率分析：\n   - 点击'添加文件'或'添加文件夹'选择要分析的内容\n   - 设置压缩算法、级别和格式\n   - 点击'开始分析'查看压缩率对比\n快捷键说明：\n- Ctrl+A：添加文件\n- Ctrl+S：开始压缩\n- ESC：取消操作\n祝您使用愉快！",
        "status_compressing": "压缩中...",
        "status_decompressing": "解压中...",
        "status_paused": "已暂停",
        "status_cancelled": "已取消",
        "status_completed": "完成",
        "lbl_algorithm": "压缩算法:",
        "lbl_compression_level": "压缩级别:",
        "lbl_compression_format": "压缩格式:",
        "group_analysis_results": "分析结果",
        "dialog_add_files": "选择文件",
        "dialog_add_folder": "选择文件夹",
        "log_analysis_cancelled": "分析已取消",
        "log_analysis_completed": "分析完成",
        "log_analysis_error": "分析出错",
        "log_analyze_item_error": "分析单个项目出错",
        "warn_no_files_selected": "请选择要分析的文件或文件夹",
        "chart_title": "压缩率对比图表",
        "chart_label_size": "文件大小",
        "tab_history": "历史记录",
        "filter_title": "过滤条件",
        "all_operations": "所有操作",
        "compression_operations": "压缩操作",
        "decompression_operations": "解压操作",
        "operation_type": "操作类型",
        "date_range": "日期范围",
        "status": "状态",
        "all_status": "所有状态",
        "success_status": "成功",
    "failed_status": "失败",
    "compression_label": "压缩",
    "decompression_label": "解压",
    "success_label": "成功",
    "failed_label": "失败",
        "reexecute": "重新执行",
        "view_details": "查看详情",
        "delete_selected": "删除选中",
        "clear_all": "清空所有",
        "no_item_selected": "请先选择要操作的历史记录",
        "operation_details": "操作详情",
        "additional_info": "附加信息",
        "selected_deleted": "已删除选中的历史记录",
        "all_history_cleared": "已清空所有历史记录",
        "warning": "警告",
        "confirmation": "确认",
        "confirm_delete_selected": "确定要删除选中的历史记录吗？",
        "confirm_clear_all": "确定要清空所有历史记录吗？",
        "btn_pause": "暂停",
        "btn_cancel": "取消",
        "btn_resume": "继续",
        "btn_verify": "验证压缩包",
        "btn_repair": "修复压缩包",
        "btn_checksum": "计算校验值",
        "btn_verify_archive": "验证压缩包",
        "btn_repair_archive": "修复压缩包",
        "btn_calculate_checksum": "计算校验值",
        "dialog_select_decompress_dir": "选择解压目录",
        "dialog_select_batch_decompress_dir": "选择批量解压目标目录",
        "dialog_save_repaired_file": "保存修复后的文件",
        "dialog_select_checksum_algorithm": "选择校验算法",
        "dialog_select_output_dir": "选择输出目录",
        "dialog_select_batch_compress_dir": "选择批量压缩目录",
        "dialog_select_target_device": "选择目标设备",
        "dialog_select_extract_dir": "选择提取目录",
        "dialog_select_add_file": "选择要添加的文件",
        "dialog_select_replace_file": "选择用于替换的文件",
        "dialog_select_modify_archive": "选择要修改的压缩包",
        "dialog_select_compress_file": "选择压缩包",
        "dialog_save_compress_file": "保存压缩文件",
        "dialog_save_file": "保存文件",
        "log_empty_archive": "压缩包为空或无法读取",
        "log_select_valid_file": "请选择有效的文件",
        "log_select_valid_archive": "请选择有效的压缩包文件",
        "log_archive_repair_failed": "压缩包修复失败",
        "log_select_files_first": "请先添加文件或文件夹",
        "log_select_output_path": "请先选择输出路径",
        "log_batch_compress_output_must_be_dir": "批量压缩时输出路径必须是目录",
        "log_select_files_to_operate": "请先选择要操作的文件或文件夹",
        "log_load_archive_first": "请先加载压缩包内容",
        "log_add_files_folder_first": "请先添加要压缩的文件或文件夹",
        "log_select_compress_and_target_dir": "请选择压缩包和目标目录",
        "log_modification_saved": "修改已保存",
        "log_no_modifications_detected": "未检测到任何修改（新增/替换/删除）",
        "menu_extract_file": "提取文件",
        "menu_delete_file": "删除文件",
        "menu_replace_file": "替换文件",
        "menu_extract_folder": "提取文件夹",
        "menu_delete_folder": "删除文件夹",
        "btn_batch_compress": "批量压缩",
        "tooltip_batch_compress": "为每个文件创建单独的压缩包",
        "btn_auto_split": "自动适应设备",
        "tooltip_auto_split": "根据目标设备空间自动调整分卷大小",
        "btn_choose_device": "选择设备",
        "btn_smart_compress": "智能压缩",
        "tooltip_smart_compress": "根据文件类型自动选择最佳压缩算法和级别",
        "tree_header_filename": "文件名",
        "tree_header_size": "大小",
        "tree_header_modified": "修改时间",
        "tree_header_compression": "压缩率",
        "btn_load_archive": "加载压缩包内容",
        "btn_extract_file": "提取选中文件",
        "btn_delete_file": "删除选中文件",
        "btn_add_file": "添加文件",
        "btn_replace_file": "替换选中文件",
        "btn_save_modify": "保存修改",
        "msgbox_success": "成功",
        "msgbox_failed": "失败",
        "msgbox_info": "提示",
        "msgbox_warning": "警告",
        "msgbox_critical": "错误",
        "msgbox_complete": "完成",
        "msgbox_confirm": "确认",
        "log_compression_complete": "压缩完成",
        "log_decompression_complete": "解压完成",
        "log_batch_decompression_complete": "批量解压完成",
        "log_conversion_complete": "转换完成",
        "log_conversion_failed": "转换失败",
        "log_batch_compression_complete": "批量压缩完成",
        "log_batch_compression_failed": "批量压缩失败",
        "log_permission_error": "权限不足",
        "log_disk_space_error": "磁盘空间不足",
        "log_file_in_use_error": "文件被占用",
        "log_password_error": "密码错误",
        "log_format_error": "格式错误",
        "log_operation_completed": "操作完成",
        "log_operation_failed": "操作失败",
        "log_modification_success": "修改压缩包成功",
        "log_modification_failed": "修改压缩包失败",
        "dialog_preview": "预览",
        "tree_header_name": "文件/目录",
        "tree_header_path": "路径",
        "dialog_search_results": "搜索结果",
        "log_no_matching_content": "未找到匹配的内容",
        "log_please_select_file": "请选择文件",
        "log_please_select_folder": "请选择文件夹",
        "log_select_compress_to_decompress": "请选择要解压的压缩包",
        "log_select_file_to_add": "请选择要添加的文件",
        "log_select_file_to_replace": "请选择要替换的文件",
        "log_select_file_to_extract": "请选择要提取的文件",
        "log_select_file_to_delete": "请选择要删除的文件",
        "log_only_select_one_item": "请只选择一个项目",
        "log_no_selection": "没有选择任何项目",
        "log_analysis_in_progress": "分析进行中...",
        "log_compression_in_progress": "压缩进行中...",
        "log_decompression_in_progress": "解压进行中...",
        "log_modification_in_progress": "修改进行中...",
        "log_batch_operation_in_progress": "批量操作进行中...",
        "log_cancelling_operation": "正在取消操作...",
        "log_operation_cancelled": "操作已取消",
        "log_operation_paused": "操作已暂停",
        "log_operation_resumed": "操作已继续",
        "log_file_already_exists": "文件已存在",
        "log_folder_already_exists": "文件夹已存在",
        "log_overwrite_existing_file": "是否覆盖已存在的文件？",
        "log_overwrite_existing_folder": "是否覆盖已存在的文件夹？",
        "log_file_not_found": "文件未找到",
        "log_folder_not_found": "文件夹未找到",
        "log_invalid_path": "无效的路径",
        "log_invalid_file": "无效的文件",
        "log_invalid_archive": "无效的压缩包",
        "log_password_wrong_or_corrupted": "密码错误或数据已损坏",
        "log_batch_convert_cancelled": "批量转换已取消",
        "log_checksum_calculation_cancelled": "校验计算已取消",
        "log_verification_cancelled": "验证已取消",
        "log_cleaning_temp_files": "正在清理临时文件...",
        "log_batch_compress_cancelled": "批量压缩已取消",
        "log_batch_decompress_cancelled": "批量解压已取消",
        "log_verification_passed": "验证通过",
        "log_verification_failed": "验证失败",
        "log_repair_completed": "修复完成",
        "log_checksum_calculated": "校验值已计算",
        "log_file_size": "文件大小",
        "log_compressed_size": "压缩后大小",
        "log_compression_ratio": "压缩率",
        "log_original_size": "原始大小",
        "log_time_taken": "耗时",
        "log_operations_performed": "执行的操作数",
        "log_success_count": "成功数",
        "log_failure_count": "失败数",
        "log_total_count": "总数",
        "log_start_time": "开始时间",
        "log_end_time": "结束时间",
        "log_current_operation": "当前操作",
        "log_progress": "进度",
        "log_status": "状态",
        "log_result": "结果",
        "log_message": "消息",
        "log_details": "详细信息",
        "log_summary": "摘要",
        "log_info": "信息",
        "log_warning": "警告",
        "log_error": "错误",
        "log_success": "成功",
        "log_debug": "调试",
        "msgbox_compression_complete": "压缩完成",
        "msgbox_decompression_complete": "解压完成",
        "msgbox_modification_complete": "修改完成",
        "msgbox_analysis_complete": "分析完成",
        "msgbox_batch_operation_complete": "批量操作完成",
        "msgbox_compression_failed": "压缩失败",
        "msgbox_decompression_failed": "解压失败",
        "msgbox_modification_failed": "修改失败",
        "msgbox_analysis_failed": "分析失败",
        "msgbox_batch_operation_failed": "批量操作失败",
        "msgbox_verification_passed": "验证通过",
        "msgbox_verification_failed": "验证失败",
        "msgbox_repair_completed": "修复完成",
        "msgbox_repair_failed": "修复失败",
        "msgbox_checksum_calculated": "校验值已计算",
        "msgbox_checksum_calculation_failed": "校验计算失败",
        "msgbox_file_already_exists": "文件已存在",
        "msgbox_folder_already_exists": "文件夹已存在",
        "msgbox_overwrite_existing_file": "是否覆盖已存在的文件？",
        "msgbox_overwrite_existing_folder": "是否覆盖已存在的文件夹？",
        "msgbox_file_not_found": "文件未找到",
        "msgbox_folder_not_found": "文件夹未找到",
        "msgbox_invalid_path": "无效的路径",
        "msgbox_invalid_file": "无效的文件",
        "msgbox_invalid_archive": "无效的压缩包",
        "msgbox_password_wrong_or_corrupted": "密码错误或数据已损坏",
        "msgbox_permission_error": "权限不足",
        "msgbox_disk_space_error": "磁盘空间不足",
        "msgbox_file_in_use_error": "文件被占用",
        "msgbox_format_error": "格式错误",
        "msgbox_operation_cancelled": "操作已取消",
        "msgbox_operation_paused": "操作已暂停",
        "msgbox_operation_resumed": "操作已继续",
        "msgbox_select_files_first": "请先添加文件或文件夹",
        "msgbox_select_output_path": "请先选择输出路径",
        "msgbox_select_files_to_operate": "请先选择要操作的文件或文件夹",
        "msgbox_load_archive_first": "请先加载压缩包内容",
        "msgbox_add_files_folder_first": "请先添加要压缩的文件或文件夹",
        "msgbox_select_compress_and_target_dir": "请选择压缩包和目标目录",
        "msgbox_select_valid_file": "请选择有效的文件",
        "msgbox_select_valid_archive": "请选择有效的压缩包文件",
        "msgbox_no_selection": "没有选择任何项目",
        "msgbox_only_select_one_item": "请只选择一个项目",
        "msgbox_please_select_file": "请选择文件",
        "msgbox_please_select_folder": "请选择文件夹",
        "msgbox_select_compress_to_decompress": "请选择要解压的压缩包",
        "msgbox_select_file_to_add": "请选择要添加的文件",
        "msgbox_select_file_to_replace": "请选择要替换的文件",
        "msgbox_select_file_to_extract": "请选择要提取的文件",
        "msgbox_select_file_to_delete": "请选择要删除的文件",
        "msgbox_empty_archive": "压缩包为空或无法读取",
        "msgbox_batch_compress_output_must_be_dir": "批量压缩时输出路径必须是目录",
        "msgbox_modification_saved": "修改已保存",
        "msgbox_no_modifications_detected": "未检测到任何修改（新增/替换/删除）",
        "msgbox_modification_success": "修改压缩包成功",
        "msgbox_modification_failed": "修改压缩包失败",
        "msgbox_help_document": "帮助文档",
        "msgbox_about": "关于",
        "msgbox_license": "许可证",
        "msgbox_changelog": "更新日志",
        "msgbox_contacts": "联系方式",
        "msgbox_feedback": "反馈",
        "msgbox_support": "支持",
        "msgbox_donate": "捐赠",
        "msgbox_rate": "评分",
        "msgbox_share": "分享",
        "msgbox_review": "评价",
        "msgbox_report_bug": "报告bug",
        "msgbox_request_feature": "请求功能",
        "msgbox_update": "更新",
        "msgbox_check_for_updates": "检查更新",
        "msgbox_download_update": "下载更新",
        "msgbox_install_update": "安装更新",
        "msgbox_update_available": "有可用更新",
        "msgbox_no_update_available": "没有可用更新",
        "msgbox_update_failed": "更新失败",
        "msgbox_update_successful": "更新成功",
        "msgbox_restart_required": "需要重启",
        "msgbox_restart_now": "立即重启",
        "msgbox_restart_later": "稍后重启",
        "msgbox_cancel_update": "取消更新",
        "msgbox_ok": "确定",
        "msgbox_cancel": "取消",
        "msgbox_yes": "是",
        "msgbox_no": "否",
        "msgbox_apply": "应用",
        "msgbox_reset": "重置",
        "msgbox_save": "保存",
        "msgbox_discard": "放弃",
        "msgbox_close": "关闭",
        "msgbox_exit": "退出",
        "msgbox_minimize": "最小化",
        "msgbox_maximize": "最大化",
        "msgbox_restore": "还原",
        "msgbox_fullscreen": "全屏",
        "msgbox_exit_fullscreen": "退出全屏",
        "msgbox_help": "帮助",
        "msgbox_about": "关于",
        "msgbox_license": "许可证",
        "msgbox_changelog": "更新日志",
        "msgbox_contacts": "联系方式",
        "msgbox_feedback": "反馈",
        "msgbox_support": "支持",
        "msgbox_donate": "捐赠",
        "msgbox_rate": "评分",
        "msgbox_share": "分享",
        "msgbox_review": "评价",
        "msgbox_report_bug": "报告bug",
        "msgbox_request_feature": "请求功能",
        "msgbox_update": "更新",
        "msgbox_check_for_updates": "检查更新",
        "msgbox_download_update": "下载更新",
        "msgbox_install_update": "安装更新",
        "msgbox_update_available": "有可用更新",
        "msgbox_no_update_available": "没有可用更新",
        "msgbox_update_failed": "更新失败",
        "msgbox_update_successful": "更新成功",
        "msgbox_restart_required": "需要重启",
        "msgbox_restart_now": "立即重启",
        "msgbox_restart_later": "稍后重启",
        "msgbox_cancel_update": "取消更新",
        "btn_batch_compress": "批量压缩",
        "chk_batch_compress": "批量压缩",
        "tooltip_batch_compress": "为每个文件创建单独的压缩包",
        "chk_auto_split": "自动适应设备",
        "tooltip_auto_split": "根据目标设备空间自动调整分卷大小",
        "btn_choose_device": "选择设备",
        "chk_smart_compress": "智能压缩",
        "tooltip_smart_compress": "根据文件类型自动选择最佳压缩算法和级别",
        "tree_files_header": ["文件名", "大小", "修改时间", "压缩率"],
        "tree_files_preview_header": ["文件/目录", "大小", "修改时间"],
        "tree_search_results_header": ["文件路径", "匹配次数"]
    },
    "en": {
        "window_title": "STZ Compression Tool",
        "btn_help": "Help",
        "tab_compress": "Compress",
        "tab_decompress": "Decompress",
        "tab_modify": "Modify Archive",
        "tab_analyze": "Compression Analysis",
        "btn_add_files": "Add Files",
        "btn_add_folders": "Add Folders",
        "btn_add_folder": "Add Folder",
        "btn_remove": "Remove Selected",
        "btn_clear": "Clear All",
        "btn_clear_list": "Clear List",
        "check_password": "Encrypt with Password",
        "edit_password": "Password",
        "use_custom_dictionary": "Use Custom Dictionary",
        "status_ready": "Ready",
        "status_compressing": "Compressing...",
        "status_decompressing": "Decompressing...",
        "status_paused": "Paused",
        "status_cancelled": "Cancelled",
        "status_completed": "Completed",
        "btn_compress_start": "Start Compression",
        "btn_decompress_start": "Start Decompression",
        "btn_modify_start": "Save Changes",
        "btn_start_analyze": "Start Analysis",
        "btn_browse": "Browse...",
        "btn_browse_compress": "Browse...",
        "btn_browse_decompress": "Browse...",
        "btn_browse_modify": "Browse...",
        "btn_load_content": "Load Content",
        "btn_preview_content": "Preview Content",
        "btn_pause": "Pause",
        "search": "Search:",
        "btn_cancel": "Cancel",
        "btn_extract": "Extract Selected Files",
        "btn_delete": "Delete Selected Files",
        "btn_addnew": "Add New Files",
        "btn_replace": "Replace Selected Files",
        "btn_stz_to_zip": "STZ -> ZIP",
        "btn_zip_to_stz": "ZIP -> STZ",
        "btn_batch_decompress": "Batch Extract STZ",
        "btn_save_modify": "Save Changes",
        "status_ready": "Ready",
        "compress_level": "Compression Level:",
        "split_size": "Split Size (MB):",
        "only_new": "Only New/Modified (Incremental)",
        "delete_source": "Delete Source After Compression",
        "output_file": "Output File (.stz):",
        "compress_file": "Select Archive (.stz):",
        "decompress_dir": "Extract Directory:",
        "theme_label": "Theme:",
        "theme_system": "System Default",
        "theme_light": "Light Theme",
        "theme_dark": "Dark Theme",
        "language_label": "Language:",
        "language_zh": "中文",
        "language_en": "English",
        "guide_title": "User Guide",
        "guide_welcome": "Welcome to STZ Compression Tool!",
        "guide_steps": "Usage Steps:\n1. Compress Files:\n   - Click 'Add Files' or 'Add Folders' to select files\n   - Set compression level, password, etc.\n   - Select output path and click 'Start Compression'\n2. Decompress Files:\n   - Select archive to decompress\n   - Set target directory\n   - Click 'Start Decompression'\n3. Modify Archive:\n   - Select archive to modify\n   - Add or remove files\n   - Click 'Save Changes'\n4. Compression Analysis:\n   - Click 'Add Files' or 'Add Folder' to select content to analyze\n   - Set compression algorithm, level and format\n   - Click 'Start Analysis' to view compression ratio comparison\nKeyboard Shortcuts:\n- Ctrl+A: Add Files\n- Ctrl+S: Start Compression\n- ESC: Cancel Operation\nEnjoy your experience!",
        "status_ready": "Ready",
        "status_compressing": "Compressing...",
        "status_decompressing": "Decompressing...",
        "status_paused": "Paused",
        "status_cancelled": "Cancelled",
        "status_completed": "Completed",
        "lbl_algorithm": "Algorithm:",
        "lbl_compression_level": "Compression Level:",
        "lbl_compression_format": "Compression Format:",
        "group_analysis_results": "Analysis Results",
        "dialog_add_files": "Select Files",
        "dialog_add_folder": "Select Folder",
        "log_analysis_cancelled": "Analysis cancelled",
        "log_analysis_completed": "Analysis completed",
        "log_analysis_error": "Analysis error",
        "log_analyze_item_error": "Error analyzing item",
        "warn_no_files_selected": "Please select files or folders to analyze",
        "chart_title": "Compression Ratio Comparison",
        "chart_label_size": "File Size",
        "tab_history": "History",
        "filter_title": "Filter",
        "all_operations": "All Operations",
        "compression_operations": "Compression Operations",
        "decompression_operations": "Decompression Operations",
        "operation_type": "Operation Type",
        "date_range": "Date Range",
        "status": "Status",
        "all_status": "All Status",
        "success_status": "Success",
    "failed_status": "Failed",
    "compression_label": "Compress",
    "decompression_label": "Decompress",
    "success_label": "Success",
    "failed_label": "Failed",
        "reexecute": "Re-execute",
        "view_details": "View Details",
        "delete_selected": "Delete Selected",
        "clear_all": "Clear All",
        "no_item_selected": "Please select a history item first",
        "operation_details": "Operation Details",
        "additional_info": "Additional Info",
        "selected_deleted": "Selected history items deleted",
        "all_history_cleared": "All history cleared",
        "warning": "Warning",
        "confirmation": "Confirmation",
        "confirm_delete_selected": "Are you sure to delete the selected history items?",
        "confirm_clear_all": "Are you sure to clear all history records?",
        "btn_pause": "Pause",
        "btn_cancel": "Cancel",
        "btn_resume": "Resume",
        "btn_verify": "Verify Archive",
        "btn_repair": "Repair Archive",
        "btn_checksum": "Calculate Checksum",
        "btn_verify_archive": "Verify Archive",
        "btn_repair_archive": "Repair Archive",
        "btn_calculate_checksum": "Calculate Checksum",
        "dialog_select_decompress_dir": "Select Decompression Directory",
        "dialog_select_batch_decompress_dir": "Select Batch Decompression Directory",
        "dialog_save_repaired_file": "Save Repaired File",
        "dialog_select_checksum_algorithm": "Select Checksum Algorithm",
        "dialog_select_output_dir": "Select Output Directory",
        "dialog_select_batch_compress_dir": "Select Batch Compression Directory",
        "dialog_select_target_device": "Select Target Device",
        "dialog_select_extract_dir": "Select Extraction Directory",
        "dialog_select_add_file": "Select File to Add",
        "dialog_select_replace_file": "Select File to Replace",
        "dialog_select_modify_archive": "Select Archive to Modify",
        "dialog_select_compress_file": "Select Archive",
        "dialog_save_compress_file": "Save Compressed File",
        "dialog_save_file": "Save File",
        "log_empty_archive": "Archive is empty or cannot be read",
        "log_select_valid_file": "Please select a valid file",
        "log_select_valid_archive": "Please select a valid archive file",
        "log_archive_repair_failed": "Archive repair failed",
        "log_select_files_first": "Please add files or folders first",
        "log_select_output_path": "Please select an output path first",
        "log_batch_compress_output_must_be_dir": "Output path must be a directory for batch compression",
        "log_select_files_to_operate": "Please select files or folders to operate",
        "log_load_archive_first": "Please load archive content first",
        "log_add_files_folder_first": "Please add files or folders to compress first",
        "log_select_compress_and_target_dir": "Please select archive and target directory",
        "log_modification_saved": "Modifications saved",
        "log_no_modifications_detected": "No modifications detected (add/replace/delete)",
        "menu_extract_file": "Extract File",
        "menu_delete_file": "Delete File",
        "menu_replace_file": "Replace File",
        "menu_extract_folder": "Extract Folder",
        "menu_delete_folder": "Delete Folder",
        "btn_batch_compress": "Batch Compress",
        "chk_batch_compress": "Batch Compress",
        "tooltip_batch_compress": "Create separate archives for each file",
        "chk_auto_split": "Auto Fit Device",
        "tooltip_auto_split": "Automatically adjust split size based on target device space",
        "btn_choose_device": "Choose Device",
        "chk_smart_compress": "Smart Compress",
        "btn_smart_compress": "Smart Compress",
        "btn_auto_split": "Auto Fit Device",
        "status_ready": "Ready",
        "tooltip_smart_compress": "Automatically select best compression algorithm and level based on file type",
        "tree_files_header": ["File Name", "Size", "Modified Time", "Compression Ratio"],
        "tree_files_preview_header": ["File/Folder", "Size", "Modified Time"],
        "tree_search_results_header": ["File Path", "Match Count"],
        "tree_header_filename": "File Name",
        "tree_header_size": "Size",
        "tree_header_modified": "Modified Time",
        "tree_header_compression": "Compression Ratio",
        "btn_load_archive": "Load Archive Content",
        "btn_extract_file": "Extract Selected Files",
        "btn_delete_file": "Delete Selected Files",
        "btn_add_file": "Add File",
        "btn_replace_file": "Replace Selected File",
        "btn_save_modify": "Save Changes",
        "msgbox_success": "Success",
        "msgbox_failed": "Failed",
        "msgbox_info": "Information",
        "msgbox_warning": "Warning",
        "msgbox_critical": "Error",
        "msgbox_complete": "Complete",
        "msgbox_confirm": "Confirmation",
        "log_compression_complete": "Compression complete",
        "log_decompression_complete": "Decompression complete",
        "log_batch_decompression_complete": "Batch decompression complete",
        "log_conversion_complete": "Conversion complete",
        "log_conversion_failed": "Conversion failed",
        "log_batch_compression_complete": "Batch compression complete",
        "log_batch_compression_failed": "Batch compression failed",
        "log_permission_error": "Permission denied",
        "log_disk_space_error": "Insufficient disk space",
        "log_file_in_use_error": "File in use",
        "log_password_error": "Password error",
        "log_format_error": "Format error",
        "log_operation_completed": "Operation completed",
        "log_operation_failed": "Operation failed",
        "log_modification_success": "Archive modification successful",
        "log_modification_failed": "Archive modification failed",
        "dialog_preview": "Preview",
        "tree_header_name": "File/Folder",
        "tree_header_path": "Path",
        "dialog_search_results": "Search Results",
        "log_no_matching_content": "No matching content found",
        "log_please_select_file": "Please select a file",
        "log_please_select_folder": "Please select a folder",
        "log_select_compress_to_decompress": "Please select archive to decompress",
        "log_select_file_to_add": "Please select file to add",
        "log_select_file_to_replace": "Please select file to replace",
        "log_select_file_to_extract": "Please select file to extract",
        "log_select_file_to_delete": "Please select file to delete",
        "log_only_select_one_item": "Please select only one item",
        "log_no_selection": "No selection",
        "log_analysis_in_progress": "Analysis in progress...",
        "log_compression_in_progress": "Compression in progress...",
        "log_decompression_in_progress": "Decompression in progress...",
        "log_modification_in_progress": "Modification in progress...",
        "log_batch_operation_in_progress": "Batch operation in progress...",
        "log_cancelling_operation": "Cancelling operation...",
        "log_operation_cancelled": "Operation cancelled",
        "log_operation_paused": "Operation paused",
        "log_operation_resumed": "Operation resumed",
        "log_file_already_exists": "File already exists",
        "log_folder_already_exists": "Folder already exists",
        "log_overwrite_existing_file": "Overwrite existing file?",
        "log_overwrite_existing_folder": "Overwrite existing folder?",
        "log_file_not_found": "File not found",
        "log_folder_not_found": "Folder not found",
        "log_invalid_path": "Invalid path",
        "log_invalid_file": "Invalid file",
        "log_invalid_archive": "Invalid archive",
        "log_password_wrong_or_corrupted": "Wrong password or corrupted data",
        "log_batch_convert_cancelled": "Batch conversion cancelled",
        "log_checksum_calculation_cancelled": "Checksum calculation cancelled",
        "log_verification_cancelled": "Verification cancelled",
        "log_cleaning_temp_files": "Cleaning temporary files...",
        "log_batch_compress_cancelled": "Batch compression cancelled",
        "log_batch_decompress_cancelled": "Batch decompression cancelled",
        "log_verification_passed": "Verification passed",
        "log_verification_failed": "Verification failed",
        "log_repair_completed": "Repair completed",
        "log_checksum_calculated": "Checksum calculated",
        "log_file_size": "File size",
        "log_compressed_size": "Compressed size",
        "log_compression_ratio": "Compression ratio",
        "log_original_size": "Original size",
        "log_time_taken": "Time taken",
        "log_operations_performed": "Operations performed",
        "log_success_count": "Success count",
        "log_failure_count": "Failure count",
        "log_total_count": "Total count",
        "log_start_time": "Start time",
        "log_end_time": "End time",
        "log_current_operation": "Current operation",
        "log_progress": "Progress",
        "log_status": "Status",
        "log_result": "Result",
        "log_message": "Message",
        "log_details": "Details",
        "log_summary": "Summary",
        "log_info": "Info",
        "log_warning": "Warning",
        "log_error": "Error",
        "log_success": "Success",
        "log_debug": "Debug",
        "msgbox_compression_complete": "Compression complete",
        "msgbox_decompression_complete": "Decompression complete",
        "msgbox_modification_complete": "Modification complete",
        "msgbox_analysis_complete": "Analysis complete",
        "msgbox_batch_operation_complete": "Batch operation complete",
        "msgbox_compression_failed": "Compression failed",
        "msgbox_decompression_failed": "Decompression failed",
        "msgbox_modification_failed": "Modification failed",
        "msgbox_analysis_failed": "Analysis failed",
        "msgbox_batch_operation_failed": "Batch operation failed",
        "msgbox_verification_passed": "Verification passed",
        "msgbox_verification_failed": "Verification failed",
        "msgbox_repair_completed": "Repair completed",
        "msgbox_repair_failed": "Repair failed",
        "msgbox_checksum_calculated": "Checksum calculated",
        "msgbox_checksum_calculation_failed": "Checksum calculation failed",
        "msgbox_file_already_exists": "File already exists",
        "msgbox_folder_already_exists": "Folder already exists",
        "msgbox_overwrite_existing_file": "Overwrite existing file?",
        "msgbox_overwrite_existing_folder": "Overwrite existing folder?",
        "msgbox_file_not_found": "File not found",
        "msgbox_folder_not_found": "Folder not found",
        "msgbox_invalid_path": "Invalid path",
        "msgbox_invalid_file": "Invalid file",
        "msgbox_invalid_archive": "Invalid archive",
        "msgbox_password_wrong_or_corrupted": "Wrong password or corrupted data",
        "msgbox_permission_error": "Permission denied",
        "msgbox_disk_space_error": "Insufficient disk space",
        "msgbox_file_in_use_error": "File in use",
        "msgbox_format_error": "Format error",
        "msgbox_operation_cancelled": "Operation cancelled",
        "msgbox_operation_paused": "Operation paused",
        "msgbox_operation_resumed": "Operation resumed",
        "msgbox_select_files_first": "Please add files or folders first",
        "msgbox_select_output_path": "Please select an output path first",
        "msgbox_select_files_to_operate": "Please select files or folders to operate",
        "msgbox_load_archive_first": "Please load archive content first",
        "msgbox_add_files_folder_first": "Please add files or folders to compress first",
        "msgbox_select_compress_and_target_dir": "Please select archive and target directory",
        "msgbox_select_valid_file": "Please select a valid file",
        "msgbox_select_valid_archive": "Please select a valid archive file",
        "msgbox_no_selection": "No selection",
        "msgbox_only_select_one_item": "Please select only one item",
        "msgbox_please_select_file": "Please select a file",
        "msgbox_please_select_folder": "Please select a folder",
        "msgbox_select_compress_to_decompress": "Please select archive to decompress",
        "msgbox_select_file_to_add": "Please select file to add",
        "msgbox_select_file_to_replace": "Please select file to replace",
        "msgbox_select_file_to_extract": "Please select file to extract",
        "msgbox_select_file_to_delete": "Please select file to delete",
        "msgbox_empty_archive": "Archive is empty or cannot be read",
        "msgbox_batch_compress_output_must_be_dir": "Output path must be a directory for batch compression",
        "msgbox_modification_saved": "Modifications saved",
        "msgbox_no_modifications_detected": "No modifications detected (add/replace/delete)",
        "msgbox_modification_success": "Archive modification successful",
        "msgbox_modification_failed": "Archive modification failed",
        "msgbox_help_document": "Help Document",
        "msgbox_about": "About",
        "msgbox_license": "License",
        "msgbox_changelog": "Changelog",
        "msgbox_contacts": "Contacts",
        "msgbox_feedback": "Feedback",
        "msgbox_support": "Support",
        "msgbox_donate": "Donate",
        "msgbox_rate": "Rate",
        "msgbox_share": "Share",
        "msgbox_review": "Review",
        "msgbox_report_bug": "Report Bug",
        "msgbox_request_feature": "Request Feature",
        "msgbox_update": "Update",
        "msgbox_check_for_updates": "Check for Updates",
        "msgbox_download_update": "Download Update",
        "msgbox_install_update": "Install Update",
        "msgbox_update_available": "Update Available",
        "msgbox_no_update_available": "No Update Available",
        "msgbox_update_failed": "Update Failed",
        "msgbox_update_successful": "Update Successful",
        "msgbox_restart_required": "Restart Required",
        "msgbox_restart_now": "Restart Now",
        "msgbox_restart_later": "Restart Later",
        "msgbox_cancel_update": "Cancel Update",
        "msgbox_ok": "OK",
        "msgbox_cancel": "Cancel",
        "msgbox_yes": "Yes",
        "msgbox_no": "No",
        "msgbox_apply": "Apply",
        "msgbox_reset": "Reset",
        "msgbox_save": "Save",
        "msgbox_discard": "Discard",
        "msgbox_close": "Close",
        "msgbox_exit": "Exit",
        "msgbox_minimize": "Minimize",
        "msgbox_maximize": "Maximize",
        "msgbox_restore": "Restore",
        "msgbox_fullscreen": "Fullscreen",
        "msgbox_exit_fullscreen": "Exit Fullscreen",
        "msgbox_help": "Help",
        "msgbox_about": "About",
        "msgbox_license": "License",
        "msgbox_changelog": "Changelog",
        "msgbox_contacts": "Contacts",
        "msgbox_feedback": "Feedback",
        "msgbox_support": "Support",
        "msgbox_donate": "Donate",
        "msgbox_rate": "Rate",
        "msgbox_share": "Share",
        "msgbox_review": "Review",
        "msgbox_report_bug": "Report Bug",
        "msgbox_request_feature": "Request Feature",
        "msgbox_update": "Update",
        "msgbox_check_for_updates": "Check for Updates",
        "msgbox_download_update": "Download Update",
        "msgbox_install_update": "Install Update",
        "msgbox_update_available": "Update Available",
        "msgbox_no_update_available": "No Update Available",
        "msgbox_update_failed": "Update Failed",
        "msgbox_update_successful": "Update Successful",
        "msgbox_restart_required": "Restart Required",
        "msgbox_restart_now": "Restart Now",
        "msgbox_restart_later": "Restart Later",
        "msgbox_cancel_update": "Cancel Update"
    }
}

# 主题样式定义
DARK_THEME_STYLE = """
    QWidget {
        background: #2b2b2b;
        color: #d4d4d4;
    }
    QLabel {
        color: #d4d4d4;
    }
    QPushButton {
        background: #3c3c3c;
        color: #d4d4d4;
        border: 1px solid #555;
        padding: 5px 10px;
        border-radius: 3px;
    }
    QPushButton:hover {
        background: #4c4c4c;
    }
    QPushButton:pressed {
        background: #5c5c5c;
    }
    QLineEdit {
        background: #3c3c3c;
        color: #d4d4d4;
        border: 1px solid #555;
        border-radius: 3px;
    }
    QComboBox {
        background: #3c3c3c;
        color: #d4d4d4;
        border: 1px solid #555;
        border-radius: 3px;
    }
    QListWidget {
        background: #3c3c3c;
        color: #d4d4d4;
        border: 1px solid #555;
        border-radius: 3px;
    }
    QListWidget::item:selected {
        background: #007acc;
        color: white;
    }
    QTextEdit {
        background: #3c3c3c;
        color: #d4d4d4;
        border: 1px solid #555;
        border-radius: 3px;
    }
    QProgressBar {
        background: #3c3c3c;
        border: 1px solid #555;
        border-radius: 3px;
        color: #d4d4d4;
    }
    QProgressBar::chunk {
        background: #007acc;
    }
"""

LIGHT_THEME_STYLE = """
    QWidget {
        background: white;
        color: black;
    }
    QPushButton {
        background: #f0f0f0;
        color: black;
        border: 1px solid #ccc;
        padding: 5px 10px;
        border-radius: 3px;
    }
    QPushButton:hover {
        background: #e0e0e0;
    }
    QPushButton:pressed {
        background: #d0d0d0;
    }
    QPushButton:disabled {
        background: #f5f5f5;
        color: #999;
        border-color: #ddd;
    }
    QListWidget {
        background: white;
        border: 1px solid #ccc;
        border-radius: 3px;
    }
    QListWidget::item {
        padding: 3px;
        border-radius: 2px;
    }
    QListWidget::item:selected {
        background: #4282d3;
        color: white;
    }
    QListWidget::item:hover {
        background: #e0ebf7;
    }
    QTextEdit {
        background: white;
        border: 1px solid #ccc;
        border-radius: 3px;
        color: black;
    }
    QProgressBar {
        background: #f0f0f0;
        border: 1px solid #ccc;
        border-radius: 3px;
        text-align: center;
        color: black;
    }
    QProgressBar::chunk {
        background: #4282d3;
        border-radius: 2px;
    }
"""

def _human_readable_size(size_bytes: int) -> str:
    """
    将字节大小转换为人类可读的格式
    
    参数:
        size_bytes: 字节大小
        decimals: 保留的小数位数
    
    返回:
        人类可读的大小字符串
    """
    if size_bytes == 0:
        return "0 B"
    size_name = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
    i = 0
    size = float(size_bytes)
    while size >= 1024 and i < len(size_name) - 1:
        size /= 1024
        i += 1
    return f"{size:.2f} {size_name[i]}"
